import Head from 'next/head'
import { ISeo } from '../../types/interface'

export const Seo = ({ title, description }: ISeo) => {
  return (
    <Head>
      <title>{title}</title>
      <meta
        name={description && description}
        content='Generated by create next app'
      />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/Pokeboll.png' />
    </Head>
  )
}
